### ISSUE TITLE
Add support for writing to analog pins

### ISSUE THREAD

**Issue by gunthercox** [zorg-framework/zorg-edison#2]
Any component, such as small speakers, usually requires writing to an analog pin. Currently there is no support for this.

**Comment by kevin-brown** [comment]
Are we talking about writing a PWM wave here?

http://iotdk.intel.com/docs/master/mraa/python/mraa.html#mraa.Pwm.write

I don't see any mention of digital to analog pins on the Edison.

**Comment by gunthercox** [comment]
I had been thinking of this in terms of the arduino, which specifies `analog_write` and `digital_write` methods. I overlooked the fact that we already have a pwm_write method defined.

Just an interesting note, for boards like the Intel Edison, and Arduino an `analog_write` function would produce a square wave, so it's technically not analog.
